//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSLocal.WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/wslco", ConfigurationName="WS.WSLCOSoap")]
    public interface WSLCOSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/wslco/UpdateLCO", ReplyAction="*")]
        void UpdateLCO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/wslco/UpdateLCO", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateLCOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/wslco/GetStatus", ReplyAction="*")]
        bool GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/wslco/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> GetStatusAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSLCOSoapChannel : WSLocal.WS.WSLCOSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSLCOSoapClient : System.ServiceModel.ClientBase<WSLocal.WS.WSLCOSoap>, WSLocal.WS.WSLCOSoap {
        
        public WSLCOSoapClient() {
        }
        
        public WSLCOSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSLCOSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLCOSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLCOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateLCO() {
            base.Channel.UpdateLCO();
        }
        
        public System.Threading.Tasks.Task UpdateLCOAsync() {
            return base.Channel.UpdateLCOAsync();
        }
        
        public bool GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public System.Threading.Tasks.Task<bool> GetStatusAsync() {
            return base.Channel.GetStatusAsync();
        }
    }
}
